### ISSUE TITLE
Run Win32AppServiceClient as Admin

### ISSUE THREAD

**Issue by jayfar** [arunjeetsingh/SampleCode#4]
Your code is great! Exactly what I need to do, but when I run the Win32AppServiceClient  exe as an administrator, it says it cannot find the App Service. How can Win32AppServiceClient  run as admin and connect to the app service?

Thanks!

**Comment by arunjeetsingh** [comment]
Unfortunately it can't as far as I know. It's been a while since I played with this code but from what I remember both the Win32 process and the app service must run as the same user (the currently logged on user). As far as I know, there's no way to run a UWP process (the app service) as admin.
